<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>k</string>
	</array>
	<key>name</key>
	<string>K</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.k</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.k</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.k</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\\\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>string-interpolation</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.k</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\+</string>
							<key>name</key>
							<string>keyword.operator.k</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key> <!--> Colour RED!!! <-->
			<string>\b(syntax(\s)+([a-z]|[a-z]\S+|[0-9]|[0-9]\S+))\b</string>
			<key>name</key>
			<string>error-token</string>
		</dict>
		<dict>
			<key>match</key> <!--> Colour light-blue <-->
			<string>(!\b[A-Z]+(\w)*\b)|(\$\b[A-Z]+(\w)*\b)</string>
			<key>name</key>
			<string>support.type.property-name.k</string>
		</dict>
		<dict>
			<key>match</key> <!--> Colour light-blue <-->
			<string>HOLE</string>
			<key>name</key>
			<string>support.type.property-name.k</string>
		</dict>
		<dict>
		    <key>match</key> <!--> Colour Light-red <-->
			<string>\b(strict|avoid|prefer|bracket|non-assoc|seqstrict|left|right|macro|token|notInRules|autoReject|structural)\b</string>
			<key>name</key>
			<string>string.regexp.k</string>
		</dict>
		<dict>
			<key>match</key> <!--> Colour blue  <-->
			<string>\b(syntax|rule|Id|Int|Bool|String|configuration|imports|Token|Lexer|Float|requires|Kresult|context)\b</string>
			<key>name</key>
			<string>keyword.reserved.k</string>
		</dict>
		<dict>
			<key>match</key> <!--> Colour orange <-->
			<string>\b(module|endmodule)\b</string>
			<key>name</key>
			<string>warn-token</string>
		</dict>
		<dict>
			<key>match</key> <!--> Colour Light green <-->
			<string>(-|\.)?\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.k</string>
		</dict>
		<dict>
			<key>match</key> <!--> tags <-->
			<string>&lt;\/?[\w\d]*&gt;</string>
			<key>name</key>
			<string>constant.regexp.emphasis.strong.tags.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|/|\*|%|=|\^|~|\||\?|&lt;|&gt;|&amp;</string>
			<key>name</key>
			<string>keyword.operator.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)\w+(?=\.|\s|,|;|\)|\?|\+|\-|=)</string>
			<key>name</key>
			<string>support.constant.k</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.k</string>
</dict>
</plist>
